# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0a9da429d0c96d93bad1ae8f2c4134a6a9a7b6ae664c56f09854f7ca9fe57fbacadd863f3bf73a063bb3ee424538ebe77c4ccfe1ff74e6cc1a9871ae401f0b

test:
  secret_key_base: 2bff1c90e17881db39f76285d0610ff3e160c189518894e943801af18ed35f700a4f9dfd9e73ac5f1102c58338d7946a8424447afdb9fba12b988d7c203b165a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
